@echo off
setlocal enabledelayedexpansion
title JARVIS - One-Click Installer
color 0B

cls
echo.
echo  ============================================================
echo                    J . A . R . V . I . S
echo            Just A Rather Very Intelligent System
echo                    One-Click Installer
echo  ============================================================
echo.
echo   This will:
echo     1. Check that Node.js is installed (and a recent version)
echo     2. Ask for your Anthropic API key
echo     3. Ask what JARVIS should call you
echo     4. Install everything automatically (5-10 minutes)
echo     5. Build the user interface
echo.
echo   When it's done, run start_jarvis.bat to launch it.
echo  ============================================================
echo.
pause

:: ======================== STEP 1: Node.js =================================
cls
echo.
echo  [Step 1 of 5]  Checking Node.js...
echo.

where node >nul 2>&1
if errorlevel 1 (
    echo  [X] Node.js is NOT installed.
    echo.
    echo  Please install Node.js 18 or newer from:
    echo.
    echo      https://nodejs.org/
    echo.
    echo  Pick the LTS button on the homepage. Run the installer and
    echo  accept all defaults. Then run this INSTALL.bat again.
    echo.
    start https://nodejs.org/
    pause
    exit /b 1
)

for /f "delims=v" %%v in ('node --version') do set NODE_VER=%%v
for /f "tokens=1 delims=." %%a in ("!NODE_VER!") do set NODE_MAJOR=%%a

if !NODE_MAJOR! LSS 18 (
    echo  [X] Node.js !NODE_VER! is too old. JARVIS needs version 18 or newer.
    echo.
    echo  Download a newer version from https://nodejs.org/
    echo.
    start https://nodejs.org/
    pause
    exit /b 1
)

echo  [OK] Node.js v!NODE_VER! detected. Looks good.
echo.
timeout /t 1 /nobreak >nul

:: ======================== STEP 2: API key =================================
cls
echo.
echo  [Step 2 of 5]  Anthropic API key
echo  ============================================================
echo.
echo   JARVIS uses Anthropic's Claude AI to think and respond.
echo   You need an API key. It's pay-as-you-go (very cheap for
echo   personal use - usually under $1/day even with heavy use).
echo.
echo   Get a key here (takes ~2 minutes):
echo.
echo       https://console.anthropic.com/
echo.
echo   1. Sign up / log in
echo   2. Click "Get API keys" or go to Settings -^> API Keys
echo   3. Click "Create Key"
echo   4. Copy the key (it starts with sk-ant-)
echo.
echo  ============================================================
echo.

:ASK_KEY
set "ANTHROPIC_KEY="
set /p "ANTHROPIC_KEY=  Paste your API key here (or press Enter to skip): "

if "!ANTHROPIC_KEY!"=="" (
    echo.
    echo  [!] Skipping for now. You can edit .env manually later.
    echo      JARVIS will not work until a real key is set.
    set "ANTHROPIC_KEY=your-anthropic-api-key-here"
    timeout /t 2 /nobreak >nul
    goto ASK_NAME
)

echo !ANTHROPIC_KEY! | findstr /B "sk-ant-" >nul
if errorlevel 1 (
    echo.
    echo  [!] That doesn't look like an Anthropic key.
    echo      Anthropic keys start with "sk-ant-..."
    echo      Try again, or press Enter to skip.
    echo.
    goto ASK_KEY
)

echo.
echo  [OK] API key looks valid.
timeout /t 1 /nobreak >nul

:ASK_NAME
echo.
echo  ============================================================
echo.
set "USER_NAME=sir"
set /p "USER_NAME=  What should JARVIS call you? (default: sir): "
if "!USER_NAME!"=="" set "USER_NAME=sir"
echo.
echo  [OK] JARVIS will address you as: !USER_NAME!
timeout /t 1 /nobreak >nul

:: ======================== STEP 3: Write .env ==============================
echo.
echo  [Step 3 of 5]  Writing configuration...
echo.

(
echo # JARVIS configuration - generated by INSTALL.bat
echo ANTHROPIC_API_KEY=!ANTHROPIC_KEY!
echo USER_NAME=!USER_NAME!
echo.
echo # FREE JARVIS voice ^(Microsoft Edge neural^). No API key needed.
echo # Options: en-GB-RyanNeural, en-GB-ThomasNeural, en-US-GuyNeural,
echo #          en-US-TonyNeural, en-GB-SoniaNeural
echo JARVIS_VOICE=en-GB-RyanNeural
echo JARVIS_RATE=+0%%
echo JARVIS_PITCH=-5%%
echo.
echo # Server
echo HOST=0.0.0.0
echo PORT=8000
echo USE_HTTPS=auto
echo.
echo # Model
echo CLAUDE_MODEL=claude-haiku-4-5-20251001
) > .env

echo  [OK] .env file written.
echo.
timeout /t 1 /nobreak >nul

:: ======================== STEP 4: Install deps ============================
cls
echo.
echo  [Step 4 of 5]  Installing dependencies (5-10 minutes)
echo  ============================================================
echo.
echo   Installing backend (Node.js packages)...
echo.

call npm install --no-fund --no-audit
if errorlevel 1 (
    echo.
    echo  [X] Backend install failed.
    echo.
    echo  Common fixes:
    echo    - Make sure you have internet access
    echo    - Try running this script as Administrator
    echo    - If "better-sqlite3" fails to build, install Visual Studio
    echo      Build Tools: https://visualstudio.microsoft.com/downloads/
    echo      (under "Tools for Visual Studio" -^> "Build Tools",
    echo      pick "Desktop development with C++")
    echo.
    pause
    exit /b 1
)

echo.
echo  [OK] Backend installed.
echo.
echo   Installing frontend (browser UI)...
echo.

cd frontend
call npm install --no-fund --no-audit
if errorlevel 1 (
    echo.
    echo  [X] Frontend install failed.
    cd ..
    pause
    exit /b 1
)
echo.
echo  [OK] Frontend dependencies installed.
echo.
echo   Building the UI...
echo.

call npm run build
if errorlevel 1 (
    echo.
    echo  [X] Frontend build failed.
    cd ..
    pause
    exit /b 1
)
cd ..

echo  [OK] UI built.
echo.
timeout /t 1 /nobreak >nul

:: ======================== STEP 5: Data dirs ===============================
echo.
echo  [Step 5 of 5]  Creating folders...
echo.

if not exist "%USERPROFILE%\Documents\JARVIS" (
    mkdir "%USERPROFILE%\Documents\JARVIS"
)
if not exist "%USERPROFILE%\Documents\JARVIS Notes" (
    mkdir "%USERPROFILE%\Documents\JARVIS Notes"
)
if not exist "%USERPROFILE%\Documents\JARVIS Projects" (
    mkdir "%USERPROFILE%\Documents\JARVIS Projects"
)
echo  [OK] Created JARVIS folders in Documents.
echo.

:: ======================== Done ============================================
cls
echo.
color 0A
echo  ============================================================
echo.
echo                     INSTALL COMPLETE!
echo.
echo  ============================================================
echo.
echo   To start JARVIS, run:
echo.
echo       start_jarvis.bat
echo.
echo   When it starts:
echo     1. It will print a URL like https://localhost:8000
echo     2. It will also print a QR code for your phone
echo     3. Open the URL in Chrome or Edge
echo     4. Click anywhere on the page
echo     5. Allow microphone access
echo     6. Start talking!
echo.
echo   First time, your browser will warn about the certificate.
echo   That's normal - it's a self-signed cert for your own PC.
echo   Click "Advanced" then "Proceed to localhost".
echo.
echo  ============================================================
echo.

choice /M "  Launch JARVIS now"
if errorlevel 2 (
    echo.
    pause
    exit /b 0
)

echo.
echo  Launching...
echo.
call start_jarvis.bat
